/**
 * Enterprise Demo Dataset — YAPRAK KATEGORİ ÜRETİM PROFİLLERİ.
 *
 * Her `kind` için: fiyat bandı (minor/kuruş), KDV, marka alanı, ürün-payı ağırlığı,
 * variant-defining eksenler (option havuzundan örnekleme aralığı), ürün-seviyesi
 * attribute'lar (facet/searchable bayrakları) ve ad/açıklama üretimi için seri havuzları.
 *
 * Arama/facet testlerinin çalışması için anahtar kelimeler (renk, kapasite, "Gaming",
 * "Bluetooth", "Sneaker", "Kahve Makinesi", "Laptop") başlık/açıklamaya profil üzerinden
 * enjekte edilir.
 */

// axis: variant-defining eksen. min/max = üründe kullanılacak option ADEDİ (havuzdan örneklem).
const axis = (code, min, max) => ({ code, min, max });
// pAttr: ürün-seviyesi attribute. select türleri option'dan seçilir; int rastgele aralıktan.
const pick = (code, { required = false, filterable = true, searchable = false } = {}) => ({
  code,
  required,
  filterable,
  searchable,
  value: "pick",
});
const intAttr = (code, min, max, { required = false, filterable = true, searchable = false } = {}) => ({
  code,
  required,
  filterable,
  searchable,
  value: "int",
  intRange: [min, max],
});

export const LEAF_PROFILES = {
  phone: {
    priceBand: [800000, 7000000],
    vatBps: 2000,
    brandDomain: "tech",
    share: 8,
    noun: "Akıllı Telefon",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 2, 4), axis("depolama", 2, 3)],
    productAttrs: [pick("isletim_sistemi", { filterable: true })],
    tags: [],
    series: ["Galaxy S24", "Galaxy A55", "Redmi Note 13", "iPhone 15", "Reno 12", "Magic 6", "Nord 4", "Edge 50"],
  },
  laptop: {
    priceBand: [1200000, 9000000],
    vatBps: 2000,
    brandDomain: "tech",
    share: 7,
    noun: "Dizüstü Bilgisayar",
    mediaAxis: null,
    variantAxes: [axis("ram_kapasitesi", 2, 2), axis("ssd_kapasitesi", 2, 2)],
    productAttrs: [
      pick("islemci", { required: true, filterable: true, searchable: true }),
      pick("ekran_karti", { filterable: true, searchable: true }),
      pick("ekran_boyutu", { filterable: true }),
      pick("isletim_sistemi", { filterable: true }),
    ],
    tags: ["Gaming", "Laptop", "Ultrabook"],
    series: ["Vivobook", "IdeaPad", "Nirvana", "Tulpar", "Excalibur", "ThinkPad", "MacBook Air", "Modern 14"],
  },
  desktop: {
    priceBand: [1000000, 12000000],
    vatBps: 2000,
    brandDomain: "tech",
    share: 3,
    noun: "Masaüstü Bilgisayar",
    mediaAxis: null,
    variantAxes: [axis("ram_kapasitesi", 2, 2), axis("ssd_kapasitesi", 2, 2)],
    productAttrs: [
      pick("islemci", { required: true, filterable: true, searchable: true }),
      pick("ekran_karti", { filterable: true, searchable: true }),
    ],
    tags: ["Gaming", "İş İstasyonu"],
    series: ["Nirvana Pro", "Excalibur Tower", "Aegis", "Optiplex", "ROG Strix"],
  },
  monitor: {
    priceBand: [300000, 3500000],
    vatBps: 2000,
    brandDomain: "tech",
    share: 3,
    noun: "Monitör",
    mediaAxis: null,
    variantAxes: [axis("ekran_boyutu", 2, 3), axis("yenileme_hizi", 2, 2)],
    productAttrs: [pick("cozunurluk", { filterable: true })],
    tags: ["Gaming", "Curved", "IPS"],
    series: ["Odyssey", "ProArt", "UltraGear", "TUF", "V-Series"],
  },
  headphone: {
    priceBand: [30000, 1500000],
    vatBps: 2000,
    brandDomain: "tech",
    share: 5,
    noun: "Kulaklık",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 2, 3)],
    productAttrs: [pick("baglanti", { filterable: true, searchable: true })],
    tags: ["Bluetooth", "Kablosuz", "Gaming", "ANC"],
    series: ["Tune", "WH-Serisi", "Zone", "Buds", "Freebuds"],
  },
  smartwatch: {
    priceBand: [150000, 4000000],
    vatBps: 2000,
    brandDomain: "tech",
    share: 3,
    noun: "Akıllı Saat",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 2, 3)],
    productAttrs: [pick("baglanti", { filterable: true })],
    tags: ["GPS", "Bluetooth", "Amoled"],
    series: ["Galaxy Watch 6", "Watch Fit", "Band 8", "GT 4", "Watch SE"],
  },
  tablet: {
    priceBand: [400000, 4500000],
    vatBps: 2000,
    brandDomain: "tech",
    share: 3,
    noun: "Tablet",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 2, 2), axis("depolama", 2, 2)],
    productAttrs: [pick("isletim_sistemi", { filterable: true })],
    tags: [],
    series: ["Galaxy Tab S9", "iPad", "Pad 6", "MatePad", "Tab P11"],
  },
  ram: {
    priceBand: [40000, 600000],
    vatBps: 2000,
    brandDomain: "tech",
    share: 3,
    noun: "RAM Bellek",
    mediaAxis: null,
    variantAxes: [axis("ram_kapasitesi", 2, 3)],
    productAttrs: [],
    tags: ["DDR4", "DDR5", "Gaming"],
    series: ["Fury Beast", "Vengeance", "Ripjaws", "Dominator"],
  },
  ssd: {
    priceBand: [50000, 1200000],
    vatBps: 2000,
    brandDomain: "tech",
    share: 3,
    noun: "SSD Disk",
    mediaAxis: null,
    variantAxes: [axis("ssd_kapasitesi", 2, 3)],
    productAttrs: [],
    tags: ["NVMe", "SATA", "M.2"],
    series: ["NV2", "MP600", "970 EVO", "A400"],
  },
  gpu: {
    priceBand: [400000, 9000000],
    vatBps: 2000,
    brandDomain: "tech",
    share: 2,
    noun: "Ekran Kartı",
    mediaAxis: null,
    variantAxes: [],
    productAttrs: [pick("ekran_karti", { required: true, filterable: true, searchable: true })],
    tags: ["Gaming", "OC"],
    series: ["Dual", "Gaming X", "Ventus", "Eagle"],
  },
  "womens-apparel": {
    priceBand: [20000, 400000],
    vatBps: 1000,
    brandDomain: "fashion",
    share: 9,
    noun: "Kadın",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 2, 3), axis("beden", 4, 5)],
    productAttrs: [
      pick("materyal", { required: true, filterable: true, searchable: true }),
      pick("kalip", { filterable: true }),
      pick("sezon", { filterable: true }),
    ],
    tags: [],
    series: ["Basic Tişört", "Triko Kazak", "Midi Elbise", "Mom Jean", "Oversize Sweatshirt", "Gömlek", "Tayt"],
  },
  "mens-apparel": {
    priceBand: [20000, 500000],
    vatBps: 1000,
    brandDomain: "fashion",
    share: 8,
    noun: "Erkek",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 2, 3), axis("beden", 4, 5)],
    productAttrs: [
      pick("materyal", { required: true, filterable: true, searchable: true }),
      pick("kalip", { filterable: true }),
      pick("yaka_tipi", { filterable: true }),
    ],
    tags: [],
    series: ["Basic Tişört", "Polo Tişört", "Slim Jean", "Sweatshirt", "Gömlek", "Şort", "Mont"],
  },
  shoes: {
    priceBand: [40000, 1200000],
    vatBps: 1000,
    brandDomain: "fashion",
    share: 6,
    noun: "Ayakkabı",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 2, 2), axis("numara", 4, 6)],
    productAttrs: [pick("materyal", { filterable: true, searchable: true }), pick("sezon", { filterable: true })],
    tags: ["Sneaker", "Koşu", "Bot"],
    series: ["Air Max", "Sneaker", "Runner", "Classic", "Court"],
  },
  bags: {
    priceBand: [30000, 800000],
    vatBps: 1000,
    brandDomain: "fashion",
    share: 3,
    noun: "Çanta",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 2, 4)],
    productAttrs: [pick("materyal", { required: true, filterable: true, searchable: true })],
    tags: ["Sırt Çantası", "Omuz Çantası"],
    series: ["Sırt Çantası", "El Çantası", "Omuz Çantası", "Laptop Çantası", "Bel Çantası"],
  },
  "small-appliance": {
    priceBand: [50000, 2000000],
    vatBps: 2000,
    brandDomain: "home",
    share: 5,
    noun: "",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 1, 2)],
    productAttrs: [
      pick("malzeme", { filterable: true, searchable: true }),
      intAttr("guc", 600, 2400, { filterable: true }),
    ],
    tags: [],
    series: ["Kahve Makinesi", "Su Isıtıcısı", "Blender", "Tost Makinesi", "Ütü", "Robot Süpürge", "Air Fryer"],
  },
  kitchen: {
    priceBand: [15000, 800000],
    vatBps: 2000,
    brandDomain: "home",
    share: 4,
    noun: "",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 1, 2)],
    productAttrs: [
      pick("malzeme", { required: true, filterable: true, searchable: true }),
      intAttr("parca_sayisi", 1, 12, { filterable: true }),
    ],
    tags: [],
    series: ["Tencere Seti", "Çaydanlık", "Bıçak Seti", "Tava", "Saklama Kabı Seti", "Kahve Fincanı Takımı"],
  },
  "home-textile": {
    priceBand: [20000, 500000],
    vatBps: 1000,
    brandDomain: "home",
    share: 4,
    noun: "",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 2, 3)],
    productAttrs: [pick("materyal", { required: true, filterable: true, searchable: true }), pick("sezon", { filterable: true })],
    tags: [],
    series: ["Nevresim Takımı", "Havlu Seti", "Battaniye", "Yastık", "Perde", "Halı"],
  },
  decor: {
    priceBand: [10000, 600000],
    vatBps: 2000,
    brandDomain: "home",
    share: 3,
    noun: "",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 1, 2)],
    productAttrs: [pick("malzeme", { filterable: true, searchable: true })],
    tags: [],
    series: ["Duvar Saati", "Masa Lambası", "Dekoratif Vazo", "Tablo", "Mumluk", "Ayna"],
  },
  skincare: {
    priceBand: [8000, 300000],
    vatBps: 1000,
    brandDomain: "personalcare",
    share: 4,
    noun: "",
    mediaAxis: null,
    variantAxes: [],
    productAttrs: [pick("cilt_tipi", { filterable: true }), pick("hacim", { filterable: true })],
    tags: [],
    series: ["Nemlendirici Krem", "Güneş Kremi", "Yüz Temizleme Jeli", "Serum", "Göz Kremi", "Tonik"],
  },
  haircare: {
    priceBand: [6000, 250000],
    vatBps: 1000,
    brandDomain: "personalcare",
    share: 3,
    noun: "",
    mediaAxis: null,
    variantAxes: [],
    productAttrs: [pick("cilt_tipi", { filterable: true }), pick("hacim", { filterable: true })],
    tags: [],
    series: ["Şampuan", "Saç Kremi", "Saç Maskesi", "Saç Serumu", "Köpük"],
  },
  perfume: {
    priceBand: [30000, 900000],
    vatBps: 1000,
    brandDomain: "personalcare",
    share: 3,
    noun: "Parfüm",
    mediaAxis: null,
    variantAxes: [axis("hacim", 2, 3)],
    productAttrs: [],
    tags: ["EDP", "EDT"],
    series: ["Eau de Parfum", "Kadın Parfüm", "Erkek Parfüm", "Unisex Parfüm"],
  },
  fitness: {
    priceBand: [15000, 2500000],
    vatBps: 2000,
    brandDomain: "sports",
    share: 3,
    noun: "",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 1, 2)],
    productAttrs: [pick("malzeme", { filterable: true })],
    tags: [],
    series: ["Dambıl Seti", "Yoga Matı", "Direnç Bandı", "Kettlebell", "Koşu Bandı", "Pilates Topu"],
  },
  "outdoor-apparel": {
    priceBand: [30000, 900000],
    vatBps: 1000,
    brandDomain: "sports",
    share: 3,
    noun: "Outdoor",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 2, 3), axis("beden", 3, 4)],
    productAttrs: [pick("materyal", { required: true, filterable: true, searchable: true }), pick("sezon", { filterable: true })],
    tags: ["Su Geçirmez", "Softshell"],
    series: ["Mont", "Polar", "Yağmurluk", "Trekking Pantolonu", "Şişme Ceket"],
  },
  bicycle: {
    priceBand: [200000, 4000000],
    vatBps: 2000,
    brandDomain: "sports",
    share: 2,
    noun: "Bisiklet",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 2, 2)],
    productAttrs: [pick("malzeme", { filterable: true })],
    tags: ["Dağ Bisikleti", "Şehir Bisikleti"],
    series: ["MTB", "Şehir Bisikleti", "Yol Bisikleti", "Katlanır Bisiklet"],
  },
  "baby-diaper": {
    priceBand: [15000, 120000],
    vatBps: 1000,
    brandDomain: "baby",
    share: 2,
    noun: "Bebek Bezi",
    mediaAxis: null,
    variantAxes: [axis("bez_bedeni", 3, 5)],
    productAttrs: [],
    tags: ["Aylık Paket", "Fırsat Paketi"],
    series: ["Aktif Bebek", "Premium Care", "Ekonomik Paket", "Külot Bez"],
  },
  "baby-apparel": {
    priceBand: [8000, 200000],
    vatBps: 1000,
    brandDomain: "baby",
    share: 2,
    noun: "Bebek",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 2, 2), axis("yas_araligi", 2, 3)],
    productAttrs: [pick("materyal", { filterable: true, searchable: true })],
    tags: [],
    series: ["Body", "Tulum", "Zıbın Seti", "Patik", "Şapka"],
  },
  toys: {
    priceBand: [8000, 400000],
    vatBps: 1000,
    brandDomain: "baby",
    share: 2,
    noun: "Oyuncak",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 1, 2)],
    productAttrs: [pick("yas_araligi", { filterable: true })],
    tags: [],
    series: ["Eğitici Oyuncak", "Peluş Oyuncak", "Yapı Bloğu Seti", "Uzaktan Kumandalı Araba", "Puzzle"],
  },
  stationery: {
    priceBand: [3000, 150000],
    vatBps: 2000,
    brandDomain: "office",
    share: 3,
    noun: "",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 1, 2)],
    productAttrs: [pick("malzeme", { filterable: true })],
    tags: [],
    series: ["Defter", "Tükenmez Kalem Seti", "Fosforlu Kalem", "Kuru Boya Seti", "Not Kağıdı", "Dosya"],
  },
  "office-furniture": {
    priceBand: [80000, 1500000],
    vatBps: 2000,
    brandDomain: "office",
    share: 2,
    noun: "",
    mediaAxis: "renk",
    variantAxes: [axis("renk", 1, 2)],
    productAttrs: [pick("malzeme", { filterable: true, searchable: true })],
    tags: ["Ergonomik"],
    series: ["Ofis Sandalyesi", "Çalışma Masası", "Kitaplık", "Dosya Dolabı"],
  },
};
