// TODO-166 (ADR-265) — Admin Slug & Redirect Management (SEO modülü) TR/EN etiketleri.
//
// Paylaşılan @commerce-os/i18n dict'ine DOKUNULMAZ (store-admin yerel etiket deseni — bkz.
// store-nav.tsx). `tr` şekli otoritedir; `en` aynı tipe zorlanır (drift → derleme hatası).

export type SeoLocale = "tr" | "en";

const TR = {
  redirects: {
    eyebrow: "SEO",
    title: "Yönlendirmeler",
    description:
      "Eski URL'lerin ziyaretçileri doğru sayfaya taşımasını sağlayan yönlendirme kuralları. Ürün, kategori veya marka adresi değişince otomatik oluşur; ayrıca elle kural ekleyebilirsiniz.",
    cardTitle: "Yönlendirme kuralları",
    cardDescription: "Otomatik ve manuel yönlendirmeler",
    countLabel: "{count} kural",
    create: "Yönlendirme ekle",
    loadError: "Yönlendirmeler yüklenemedi.",
    emptyTitle: "Henüz yönlendirme yok",
    emptyDescription:
      "Bir ürün, kategori veya markanın adresi değiştiğinde eski URL için otomatik bir yönlendirme oluşturulur. Elle de kural ekleyebilirsiniz.",
    searchPlaceholder: "Kaynak veya hedef adres ara",
    viewDetail: "Detay",
    table: {
      source: "Kaynak adres",
      target: "Hedef adres",
      code: "Kod",
      entityType: "İçerik türü",
      origin: "Kaynağı",
      status: "Durum",
      reason: "Oluşturulma nedeni",
      updated: "Son güncelleme",
      action: "İşlem",
    },
    filters: {
      origin: "Kaynağı",
      type: "Yönlendirme kodu",
      entityType: "İçerik türü",
      status: "Durum",
    },
    originLabels: { AUTOMATIC: "Otomatik", MANUAL: "Manuel" },
    entityLabels: { PRODUCT: "Ürün", CATEGORY: "Kategori", BRAND: "Marka", OTHER: "Diğer" },
    statusLabels: { enabled: "Aktif", disabled: "Pasif" },
    reasonAuto: "Adres değişikliği",
    reasonManual: "Elle eklendi",
    detail: {
      title: "Yönlendirme detayı",
      chain: "Yönlendirme zinciri",
      resolvedTarget: "Nihai hedef",
      chainLength: "Zincir uzunluğu",
      chainHops: "{count} adım",
      loopWarning:
        "Bu yönlendirme bir döngü oluşturuyor ve ziyaretçiye uygulanmaz. Hedefi düzeltin.",
      notes: "Not",
      noNotes: "Not eklenmemiş",
      createdAt: "Oluşturulma",
      updatedAt: "Güncelleme",
      automaticHint:
        "Bu kayıt bir adres değişikliğinden otomatik oluştu. Kaynak/hedef düzenlenemez; yalnızca aktif/pasif yapabilirsiniz.",
      enable: "Aktifleştir",
      disable: "Pasifleştir",
      edit: "Düzenle",
      delete: "Sil",
      deleteConfirm: "Bu yönlendirmeyi silmek istediğinize emin misiniz?",
    },
    form: {
      createTitle: "Yönlendirme ekle",
      createDescription:
        "Eski bir adresi (kaynak) yeni bir sayfaya (hedef) yönlendirin. Adresler mağaza içinde ve / ile başlamalıdır.",
      editTitle: "Yönlendirmeyi düzenle",
      source: "Kaynak adres",
      sourceHint: "Örn. /eski-kampanya",
      target: "Hedef adres",
      targetHint: "Örn. /products/yeni-urun",
      type: "Yönlendirme kodu",
      notes: "Not (opsiyonel)",
      enabled: "Aktif",
      submit: "Kaydet",
      cancel: "Vazgeç",
      sourceRequired: "Kaynak adres gerekli.",
      targetRequired: "Hedef adres gerekli.",
    },
    typeLabels: {
      PERMANENT_301: "301 – Kalıcı",
      FOUND_302: "302 – Geçici",
      TEMPORARY_307: "307 – Geçici",
      PERMANENT_308: "308 – Kalıcı",
    },
    sort: {
      newest: "En yeni",
      oldest: "En eski",
      sourceAsc: "Kaynak A→Z",
      sourceDesc: "Kaynak Z→A",
    },
  },
  slugs: {
    eyebrow: "SEO",
    title: "Sluglar",
    description:
      "Ürün, kategori ve markalarınızın adres (slug) bilgisi ve geçmiş adresleri. Bir adres değişince eski adres otomatik olarak yönlendirmeye dönüşür.",
    cardTitle: "Slug dizini",
    cardDescription: "Güncel adresler ve geçmişleri",
    countLabel: "{count} kayıt",
    loadError: "Sluglar yüklenemedi.",
    emptyTitle: "Kayıt bulunamadı",
    emptyDescription: "Seçilen ölçütlere uygun ürün, kategori veya marka bulunamadı.",
    searchPlaceholder: "Ad veya slug ara",
    viewDetail: "Detay",
    table: {
      slug: "Güncel slug",
      name: "İçerik",
      entityType: "Tür",
      canonical: "Canonical URL",
      status: "Durum",
      previous: "Önceki slug",
      updated: "Son güncelleme",
      action: "İşlem",
    },
    filters: {
      entityType: "İçerik türü",
      status: "Durum",
      hasRedirects: "Yönlendirmesi olanlar",
    },
    entityLabels: { PRODUCT: "Ürün", CATEGORY: "Kategori", BRAND: "Marka" },
    statusLabels: { active: "Aktif", archived: "Arşivli" },
    hasRedirectsLabels: { true: "Yönlendirmesi olanlar", false: "Yönlendirmesi olmayanlar" },
    previousCount: "{count} eski adres",
    detail: {
      title: "Slug detayı",
      canonical: "Canonical URL",
      currentSlug: "Güncel slug",
      history: "Slug geçmişi",
      historyEmpty: "Bu içeriğin adresi hiç değişmemiş; geçmiş yok.",
      previousSlug: "Eski slug",
      redirectsTo: "yönlendirir →",
      changedAt: "Değişim",
      openEntity: "İçerik ekranına git",
    },
    sort: {
      newest: "En yeni",
      oldest: "En eski",
      slugAsc: "Slug A→Z",
      nameAsc: "Ad A→Z",
    },
  },
};

type SeoDictShape = typeof TR;

const EN: SeoDictShape = {
  redirects: {
    eyebrow: "SEO",
    title: "Redirects",
    description:
      "Rules that carry visitors from old URLs to the right page. Created automatically when a product, category or brand address changes; you can also add rules manually.",
    cardTitle: "Redirect rules",
    cardDescription: "Automatic and manual redirects",
    countLabel: "{count} rules",
    create: "Add redirect",
    loadError: "Failed to load redirects.",
    emptyTitle: "No redirects yet",
    emptyDescription:
      "When a product, category or brand address changes, a redirect for the old URL is created automatically. You can also add rules manually.",
    searchPlaceholder: "Search source or target path",
    viewDetail: "Details",
    table: {
      source: "Source path",
      target: "Target path",
      code: "Code",
      entityType: "Content type",
      origin: "Origin",
      status: "Status",
      reason: "Created because",
      updated: "Last updated",
      action: "Action",
    },
    filters: {
      origin: "Origin",
      type: "Redirect code",
      entityType: "Content type",
      status: "Status",
    },
    originLabels: { AUTOMATIC: "Automatic", MANUAL: "Manual" },
    entityLabels: { PRODUCT: "Product", CATEGORY: "Category", BRAND: "Brand", OTHER: "Other" },
    statusLabels: { enabled: "Active", disabled: "Disabled" },
    reasonAuto: "Address change",
    reasonManual: "Added manually",
    detail: {
      title: "Redirect detail",
      chain: "Redirect chain",
      resolvedTarget: "Final target",
      chainLength: "Chain length",
      chainHops: "{count} hops",
      loopWarning: "This redirect forms a loop and is not applied to visitors. Fix the target.",
      notes: "Note",
      noNotes: "No note added",
      createdAt: "Created",
      updatedAt: "Updated",
      automaticHint:
        "This entry was created automatically from an address change. Source/target cannot be edited; you can only enable/disable it.",
      enable: "Enable",
      disable: "Disable",
      edit: "Edit",
      delete: "Delete",
      deleteConfirm: "Are you sure you want to delete this redirect?",
    },
    form: {
      createTitle: "Add redirect",
      createDescription:
        "Redirect an old address (source) to a new page (target). Addresses must be within the store and start with /.",
      editTitle: "Edit redirect",
      source: "Source path",
      sourceHint: "e.g. /old-campaign",
      target: "Target path",
      targetHint: "e.g. /products/new-product",
      type: "Redirect code",
      notes: "Note (optional)",
      enabled: "Active",
      submit: "Save",
      cancel: "Cancel",
      sourceRequired: "Source path is required.",
      targetRequired: "Target path is required.",
    },
    typeLabels: {
      PERMANENT_301: "301 – Permanent",
      FOUND_302: "302 – Temporary",
      TEMPORARY_307: "307 – Temporary",
      PERMANENT_308: "308 – Permanent",
    },
    sort: {
      newest: "Newest",
      oldest: "Oldest",
      sourceAsc: "Source A→Z",
      sourceDesc: "Source Z→A",
    },
  },
  slugs: {
    eyebrow: "SEO",
    title: "Slugs",
    description:
      "The address (slug) and previous addresses of your products, categories and brands. When an address changes, the old one becomes a redirect automatically.",
    cardTitle: "Slug directory",
    cardDescription: "Current addresses and their history",
    countLabel: "{count} records",
    loadError: "Failed to load slugs.",
    emptyTitle: "No records found",
    emptyDescription: "No product, category or brand matches the selected criteria.",
    searchPlaceholder: "Search name or slug",
    viewDetail: "Details",
    table: {
      slug: "Current slug",
      name: "Content",
      entityType: "Type",
      canonical: "Canonical URL",
      status: "Status",
      previous: "Previous slugs",
      updated: "Last updated",
      action: "Action",
    },
    filters: {
      entityType: "Content type",
      status: "Status",
      hasRedirects: "With redirects",
    },
    entityLabels: { PRODUCT: "Product", CATEGORY: "Category", BRAND: "Brand" },
    statusLabels: { active: "Active", archived: "Archived" },
    hasRedirectsLabels: { true: "With redirects", false: "Without redirects" },
    previousCount: "{count} old addresses",
    detail: {
      title: "Slug detail",
      canonical: "Canonical URL",
      currentSlug: "Current slug",
      history: "Slug history",
      historyEmpty: "This content's address has never changed; no history.",
      previousSlug: "Old slug",
      redirectsTo: "redirects to →",
      changedAt: "Changed",
      openEntity: "Open content screen",
    },
    sort: {
      newest: "Newest",
      oldest: "Oldest",
      slugAsc: "Slug A→Z",
      nameAsc: "Name A→Z",
    },
  },
};

const DICTS: Record<SeoLocale, SeoDictShape> = { tr: TR, en: EN };

export function seoDict(locale: string): SeoDictShape {
  return locale === "en" ? DICTS.en : DICTS.tr;
}
