/**
 * TODO-158A (ADR-086) — Home Experience admin ekranları için yerel etiketler (tr/en).
 * Paylaşılan i18n paketine yalnız nav anahtarı eklendi; ekran metinleri parity riskini
 * azaltmak için burada tutulur (store-admin yerel deseni).
 */
export type HomeLocale = "tr" | "en";

const tr = {
  eyebrow: "Ana Sayfa Deneyimi",
  title: "Ana Sayfa Bölümleri",
  description:
    "Vitrin ana sayfasını yönet: hero slider, öne çıkan kategoriler ve ürün showcase'leri. Sıra vitrinde bu sırayla görünür.",
  newSection: "Yeni bölüm",
  insightsLink: "Öneri Ölçümü",
  cardTitle: "Bölümler",
  countLabel: "{count} bölüm",
  types: {
    HERO_SLIDER: "Hero Slider",
    FEATURED_CATEGORIES: "Öne Çıkan Kategoriler",
    PRODUCT_SHOWCASE: "Ürün Showcase",
    SPONSORED_SHOWCASE: "Sponsorlu Vitrin",
    RECENTLY_VIEWED: "Son İncelediklerin",
    // TODO-162 — Keşif (eligibility-driven) section tipleri.
    DISCOVERY_GRID: "Keşif Grid'i",
    CONTINUE_BROWSING: "Kaldığın Yerden",
    CART_RECOMMENDATIONS: "Sepetine Göre Öneriler",
    PERSONALIZED_DEALS: "Sana Özel Fırsatlar",
    DAILY_DEALS: "Günün Fırsatları",
    EDITORIAL_CAMPAIGN: "Editoryal Kart",
    REPURCHASE: "Tekrar Satın Al",
    SIMILAR_TO_PURCHASED: "Aldıklarına Benzer",
    WISHLIST_DEALS: "İstek Listesi Fırsatları",
    SPONSORED_RAIL: "Sponsorlu Şerit",
  } as Record<string, string>,
  table: { type: "Tip", title: "Başlık", visibility: "Görünürlük", status: "Durum", order: "Sıra", actions: "İşlemler" },
  enabled: "Aktif",
  disabled: "Pasif",
  visibilityBoth: "Masaüstü + Mobil",
  visibilityDesktop: "Yalnız masaüstü",
  visibilityMobile: "Yalnız mobil",
  visibilityNone: "Gizli",
  manage: "Yönet",
  editSettings: "Ayarlar",
  toggleEnable: "Aktifleştir",
  toggleDisable: "Pasifleştir",
  delete: "Sil",
  moveUp: "Yukarı taşı",
  moveDown: "Aşağı taşı",
  untitled: "(başlıksız)",
  deleteConfirm: "Bu bölümü ve içeriğini silmek istediğinize emin misiniz?",
  createdToast: "Bölüm oluşturuldu.",
  updatedToast: "Bölüm güncellendi.",
  deletedToast: "Bölüm silindi.",
  emptyTitle: "Henüz bölüm yok",
  emptyDescription: "Ana sayfayı oluşturmak için bir hero, öne çıkan kategori veya ürün showcase bölümü ekleyin.",
  emptyAction: "İlk bölümü ekle",
  loadError: "Bölümler yüklenemedi.",
  retry: "Tekrar dene",
  dismiss: "Kapat",
  cancel: "İptal",
  save: "Kaydet",
  saving: "Kaydediliyor…",
  create: "Oluştur",
  form: {
    createTitle: "Yeni bölüm",
    editTitle: "Bölüm ayarları",
    typeLabel: "Bölüm tipi",
    titleLabel: "Başlık",
    subtitleLabel: "Alt başlık (eyebrow)",
    enabledLabel: "Aktif (vitrinde göster)",
    desktopVisibleLabel: "Masaüstünde görünür",
    mobileVisibleLabel: "Mobilde görünür",
    publishStartLabel: "Yayın başlangıcı (opsiyonel)",
    publishEndLabel: "Yayın bitişi (opsiyonel)",
    autoplayLabel: "Otomatik geçiş (ms, 0 = kapalı)",
    layoutLabel: "Düzen",
    layoutCarousel: "Carousel",
    layoutGrid: "Grid",
    maxItemsLabel: "Maksimum ürün",
    titleTrLabel: "Başlık (TR)",
    titleEnLabel: "Başlık (EN)",
    recentlyViewedHint:
      "İçerik her ziyaretçinin KENDİ görüntüleme geçmişinden otomatik gelir; burada ürün seçimi yapılmaz. Geçmişi olmayan ziyaretçide bu bölüm hiç gösterilmez. Başlığı boş bırakırsanız varsayılan çeviri kullanılır.",
    sponsoredHint:
      "İçerik AKTİF sponsorlu kampanyalardan (yerleşim: Ana sayfa vitrini) otomatik gelir. Ürün seçimi burada YAPILMAZ — Sponsorlu Kampanyalar modülünden yönetilir. Aktif kampanya/ürün yoksa bu bölüm gizlenir.",
    sourceLabel: "Kaynak",
    sourceManual: "Manuel (ürün seç)",
    sourceDynamic: "Dinamik (kural)",
    ruleLabel: "Kural",
    rules: {
      NEW_PRODUCTS: "Yeni Ürünler",
      CAMPAIGN: "Kampanyalı Ürünler",
      CATEGORY: "Kategori",
      BRAND: "Marka",
      ATTRIBUTE: "Özellik",
      IN_STOCK: "Stokta",
    } as Record<string, string>,
    categorySlugLabel: "Kategori slug",
    brandLabel: "Marka",
    attributeCodeLabel: "Özellik kodu",
    attributeValueLabel: "Özellik değeri",
    // TODO-162 — Keşif section config alanları.
    discoveryRailHint:
      "İçerik ziyaretçiye-özgü sinyallerden (geçmiş/sepet/istek listesi/sipariş) otomatik gelir; burada ürün seçilmez. Yeterli sinyal yoksa bu bölüm ziyaretçiye HİÇ gösterilmez (boş başlık/iskele yok). Aşağıdaki ayarlar yalnız sunum ve görünürlük sınırlarıdır.",
    discoveryGridHint:
      "Hero altı grid: içinde 2–4 UYGUN kart gösterilir. Kartları buradan seçip sıralarsın; hangi kartın gösterileceğine motor karar verir (uygun olmayan kart otomatik gizlenir). En az 2 uygun kart yoksa grid gösterilmez.",
    editorialHint:
      "Editoryal kart tamamen buradaki içerikten oluşur. Başlık ve CTA bağlantısı zorunludur; eksikse kart gösterilmez (sahte içerik üretilmez). Görsel opsiyoneldir.",
    guestSupportedLabel: "Misafir (giriş yapmamış) ziyaretçilere göster",
    authSupportedLabel: "Giriş yapmış müşterilere göster",
    fallbackDisabledLabel: "Sinyal yoksa genel içerikle doldurma (yalnız gerçek sinyalde göster)",
    boundsHint:
      "İş kuralı: en az {min}, en fazla {max} ürün. Maksimumu düşürebilirsin ama minimumu düşüremezsin (motor sınırlar).",
    boundsAuthOnly: "Yalnız giriş yapmış müşterilere gösterilir (sipariş geçmişi gerekir).",
    boundsFallback: "Gerçek sinyal yoksa genel/indirimli katalogla doldurulabilir (isteğe bağlı kapatılır).",
    editorialMediaIdLabel: "Görsel (opsiyonel — yükle veya kütüphaneden seç)",
    bodyTrLabel: "Metin (TR)",
    bodyEnLabel: "Metin (EN)",
    ctaLabelTrLabel: "CTA metni (TR)",
    ctaLabelEnLabel: "CTA metni (EN)",
    editorialCtaHrefLabel: "CTA bağlantısı (göreli yol, / ile başlar)",
    linkedCampaignIdLabel: "Bağlı kampanya ID (opsiyonel; yayın penceresi doğrulaması)",
    gridCardsLabel: "Grid kartları (sırayla)",
    gridCardsHint: "Kart ekle ve sırala. Motor yalnız uygun olanları (en fazla 4) gösterir.",
    gridAddCard: "Kart ekle",
    gridRemoveCard: "Kaldır",
    gridCardTypes: {
      CONTINUE_BROWSING: "Kaldığın Yerden",
      CART_RECOMMENDATIONS: "Sepetine Göre",
      PERSONALIZED_DEALS: "Sana Özel",
      EDITORIAL_CAMPAIGN: "Editoryal",
      DAILY_DEALS: "Günün Fırsatları",
    } as Record<string, string>,
  },
  preview: {
    link: "Keşif önizleme",
    title: "Keşif Önizleme (örnek veri)",
    eyebrow: "Simülasyon",
    description:
      "Yapılandırdığın keşif bölümlerinin farklı ziyaretçi durumlarında NASIL davranacağını gösterir. Buradaki veriler ÖRNEKTİR (gerçek müşteri verisi değildir); nihai uygunluk kararını her zaman sunucu verir.",
    disclaimer:
      "⚠ Örnek/simülasyon: gerçek ürün stoğu, indirim ve sponsor durumu sunucuda değerlendirilir. Bu önizleme yalnız sinyal eşiklerini gösterir.",
    scenarioLabel: "Ziyaretçi durumu",
    scenarios: {
      guestNoSignal: "Misafir — sinyal yok",
      guestRecentlyViewed: "Misafir — ürün geçmişi var",
      guestCart: "Misafir — sepette ürün var",
      authNoHistory: "Üye — geçmiş yok",
      authOrderHistory: "Üye — sipariş geçmişi var",
    } as Record<string, string>,
    signalsLabel: "Örnek sinyaller",
    signalRecentlyViewed: "Görüntülenen ürün",
    signalCart: "Sepetteki ürün",
    signalWishlist: "İstek listesi",
    signalOrders: "Tamamlanan sipariş",
    signalAuth: "Giriş durumu",
    authYes: "Üye",
    authNo: "Misafir",
    renderedTitle: "Gösterilecek bölümler",
    hiddenTitle: "Gizlenecek bölümler",
    noneRendered: "Bu durumda hiçbir keşif bölümü gösterilmez.",
    noDiscoverySections: "Henüz keşif tipi bir bölüm yok. Bir keşif bölümü ekleyince burada önizlenir.",
    reasonEligible: "Uygun",
    reasonNoSignal: "Yeterli sinyal yok",
    reasonRequiresAuth: "Giriş gerekli",
    reasonDisabled: "Bölüm pasif",
    reasonEditorialIncomplete: "Editoryal içerik eksik (başlık/CTA)",
    reasonGridInsufficient: "En az 2 uygun kart yok",
    reasonDependsCatalog: "Katalog/sponsor durumuna bağlı (sunucu karar verir)",
    back: "← Bölümlere dön",
  },
  detail: {
    back: "← Bölümlere dön",
    heroTitle: "Hero Slide'ları",
    heroAdd: "Slide ekle",
    heroEmpty: "Henüz slide yok. Tam genişlik hero için bir görsel ekleyin.",
    featuredTitle: "Öne Çıkan Kategoriler",
    featuredAdd: "Kategori ekle",
    featuredEmpty: "Henüz kategori seçilmedi.",
    showcaseTitle: "Showcase Ürünleri",
    showcaseDynamicInfo:
      "Bu showcase DİNAMİK kaynaklıdır; ürünler kurala göre otomatik seçilir. Manuel ürün eklemek için bölüm ayarlarından kaynağı Manuel yapın.",
    showcaseSave: "Ürünleri kaydet",
    productPickerLabel: "Ürünler (seçili sırayla gösterilir)",
    // TODO-159B (ADR-090) — Sıralama artık seçim sırasıdır; çipler o sırada durur.
    showcaseOrderHint: "Ürünler seçtiğiniz sırayla vitrinde gösterilir.",
    categoryRequired: "Lütfen bir kategori seçin.",
    selected: "seçili",
    imageLabel: "Görsel",
    mobileImageLabel: "Mobil görsel (opsiyonel)",
    imageRequired: "Hero görseli zorunludur.",
    headlineLabel: "Başlık",
    subtextLabel: "Alt metin",
    ctaLabelLabel: "CTA metni",
    ctaHrefLabel: "CTA bağlantısı",
    categoryLabel: "Kategori",
    titleOverrideLabel: "Başlık override",
    descriptionOverrideLabel: "Açıklama override",
    enabledLabel: "Aktif",
    addSlideTitle: "Slide ekle",
    editSlideTitle: "Slide düzenle",
    addCategoryTitle: "Kategori ekle",
    editCategoryTitle: "Kategori düzenle",
    image: "Görsel",
    headline: "Başlık",
    order: "Sıra",
    actions: "İşlemler",
    edit: "Düzenle",
    remove: "Kaldır",
    savedToast: "Kaydedildi.",
    removedToast: "Kaldırıldı.",
  },
};

const en: typeof tr = {
  eyebrow: "Home Experience",
  title: "Home Sections",
  description:
    "Manage the storefront home: hero slider, featured categories and product showcases. Order here is the render order on the storefront.",
  newSection: "New section",
  insightsLink: "Recommendation Insights",
  cardTitle: "Sections",
  countLabel: "{count} sections",
  types: {
    HERO_SLIDER: "Hero Slider",
    FEATURED_CATEGORIES: "Featured Categories",
    PRODUCT_SHOWCASE: "Product Showcase",
    SPONSORED_SHOWCASE: "Sponsored Showcase",
    RECENTLY_VIEWED: "Recently Viewed",
    DISCOVERY_GRID: "Discovery Grid",
    CONTINUE_BROWSING: "Continue Browsing",
    CART_RECOMMENDATIONS: "Cart Recommendations",
    PERSONALIZED_DEALS: "Personalized Deals",
    DAILY_DEALS: "Daily Deals",
    EDITORIAL_CAMPAIGN: "Editorial Card",
    REPURCHASE: "Buy Again",
    SIMILAR_TO_PURCHASED: "Similar to Purchased",
    WISHLIST_DEALS: "Wishlist Deals",
    SPONSORED_RAIL: "Sponsored Rail",
  },
  table: { type: "Type", title: "Title", visibility: "Visibility", status: "Status", order: "Order", actions: "Actions" },
  enabled: "Enabled",
  disabled: "Disabled",
  visibilityBoth: "Desktop + Mobile",
  visibilityDesktop: "Desktop only",
  visibilityMobile: "Mobile only",
  visibilityNone: "Hidden",
  manage: "Manage",
  editSettings: "Settings",
  toggleEnable: "Enable",
  toggleDisable: "Disable",
  delete: "Delete",
  moveUp: "Move up",
  moveDown: "Move down",
  untitled: "(untitled)",
  deleteConfirm: "Delete this section and its content?",
  createdToast: "Section created.",
  updatedToast: "Section updated.",
  deletedToast: "Section deleted.",
  emptyTitle: "No sections yet",
  emptyDescription: "Add a hero, featured categories or product showcase section to build the home page.",
  emptyAction: "Add first section",
  loadError: "Could not load sections.",
  retry: "Retry",
  dismiss: "Dismiss",
  cancel: "Cancel",
  save: "Save",
  saving: "Saving…",
  create: "Create",
  form: {
    createTitle: "New section",
    editTitle: "Section settings",
    typeLabel: "Section type",
    titleLabel: "Title",
    subtitleLabel: "Subtitle (eyebrow)",
    enabledLabel: "Enabled (show on storefront)",
    desktopVisibleLabel: "Visible on desktop",
    mobileVisibleLabel: "Visible on mobile",
    publishStartLabel: "Publish start (optional)",
    publishEndLabel: "Publish end (optional)",
    autoplayLabel: "Autoplay (ms, 0 = off)",
    layoutLabel: "Layout",
    layoutCarousel: "Carousel",
    layoutGrid: "Grid",
    maxItemsLabel: "Max products",
    titleTrLabel: "Title (TR)",
    titleEnLabel: "Title (EN)",
    recentlyViewedHint:
      "Content comes automatically from each visitor's OWN viewing history; no products are selected here. Visitors with no history won't see this section at all. Leave the title empty to use the default translation.",
    sponsoredHint:
      "Content comes automatically from ACTIVE sponsored campaigns (placement: Home showcase). Products are not selected here — manage them in the Sponsored Products module. If no active campaign/products, this section is hidden.",
    sourceLabel: "Source",
    sourceManual: "Manual (pick products)",
    sourceDynamic: "Dynamic (rule)",
    ruleLabel: "Rule",
    rules: {
      NEW_PRODUCTS: "New Products",
      CAMPAIGN: "Campaign Products",
      CATEGORY: "Category",
      BRAND: "Brand",
      ATTRIBUTE: "Attribute",
      IN_STOCK: "In Stock",
    },
    categorySlugLabel: "Category slug",
    brandLabel: "Brand",
    attributeCodeLabel: "Attribute code",
    attributeValueLabel: "Attribute value",
    discoveryRailHint:
      "Content comes automatically from visitor-specific signals (history/cart/wishlist/orders); no products are picked here. With insufficient signal this section is NOT shown to the visitor (no empty title/skeleton). The settings below are presentation and visibility limits only.",
    discoveryGridHint:
      "Below-hero grid: shows 2–4 ELIGIBLE cards. Pick and order cards here; the engine decides which render (ineligible cards are hidden automatically). If fewer than 2 cards are eligible the grid is not shown.",
    editorialHint:
      "The editorial card is built entirely from the content here. Title and CTA link are required; if missing the card is hidden (no fake content). Image is optional.",
    guestSupportedLabel: "Show to guest (not signed-in) visitors",
    authSupportedLabel: "Show to signed-in customers",
    fallbackDisabledLabel: "Don't fill with generic content when no signal (only show on real signal)",
    boundsHint:
      "Business rule: minimum {min}, maximum {max} products. You can lower the maximum but not the minimum (the engine clamps).",
    boundsAuthOnly: "Shown only to signed-in customers (requires order history).",
    boundsFallback: "May be filled from the generic/discounted catalog when there's no real signal (optionally disabled).",
    editorialMediaIdLabel: "Image (optional — upload or pick from library)",
    bodyTrLabel: "Body (TR)",
    bodyEnLabel: "Body (EN)",
    ctaLabelTrLabel: "CTA label (TR)",
    ctaLabelEnLabel: "CTA label (EN)",
    editorialCtaHrefLabel: "CTA link (relative path, starts with /)",
    linkedCampaignIdLabel: "Linked campaign ID (optional; publish-window check)",
    gridCardsLabel: "Grid cards (in order)",
    gridCardsHint: "Add and order cards. The engine shows only eligible ones (max 4).",
    gridAddCard: "Add card",
    gridRemoveCard: "Remove",
    gridCardTypes: {
      CONTINUE_BROWSING: "Continue Browsing",
      CART_RECOMMENDATIONS: "Cart-based",
      PERSONALIZED_DEALS: "Personalized",
      EDITORIAL_CAMPAIGN: "Editorial",
      DAILY_DEALS: "Daily Deals",
    },
  },
  preview: {
    link: "Discovery preview",
    title: "Discovery Preview (sample data)",
    eyebrow: "Simulation",
    description:
      "Shows HOW your configured discovery sections behave for different visitor states. The data here is SAMPLE (not real customer data); the final eligibility decision is always made by the server.",
    disclaimer:
      "⚠ Sample/simulation: real stock, discount and sponsor state are evaluated on the server. This preview only reflects signal thresholds.",
    scenarioLabel: "Visitor state",
    scenarios: {
      guestNoSignal: "Guest — no signal",
      guestRecentlyViewed: "Guest — has view history",
      guestCart: "Guest — has cart items",
      authNoHistory: "Member — no history",
      authOrderHistory: "Member — has order history",
    },
    signalsLabel: "Sample signals",
    signalRecentlyViewed: "Viewed products",
    signalCart: "Cart items",
    signalWishlist: "Wishlist items",
    signalOrders: "Completed orders",
    signalAuth: "Sign-in state",
    authYes: "Member",
    authNo: "Guest",
    renderedTitle: "Sections that render",
    hiddenTitle: "Sections that stay hidden",
    noneRendered: "No discovery section renders in this state.",
    noDiscoverySections: "No discovery-type section yet. Add one to preview it here.",
    reasonEligible: "Eligible",
    reasonNoSignal: "Not enough signal",
    reasonRequiresAuth: "Sign-in required",
    reasonDisabled: "Section disabled",
    reasonEditorialIncomplete: "Editorial content incomplete (title/CTA)",
    reasonGridInsufficient: "Fewer than 2 eligible cards",
    reasonDependsCatalog: "Depends on catalog/sponsor state (server decides)",
    back: "← Back to sections",
  },
  detail: {
    back: "← Back to sections",
    heroTitle: "Hero Slides",
    heroAdd: "Add slide",
    heroEmpty: "No slides yet. Add an image for the full-width hero.",
    featuredTitle: "Featured Categories",
    featuredAdd: "Add category",
    featuredEmpty: "No categories selected yet.",
    showcaseTitle: "Showcase Products",
    showcaseDynamicInfo:
      "This showcase is DYNAMIC; products are auto-selected by rule. To add manual products, switch the source to Manual in section settings.",
    showcaseSave: "Save products",
    productPickerLabel: "Products (shown in selected order)",
    showcaseOrderHint: "Products appear on the storefront in the order you select them.",
    categoryRequired: "Please select a category.",
    selected: "selected",
    imageLabel: "Image",
    mobileImageLabel: "Mobile image (optional)",
    imageRequired: "Hero image is required.",
    headlineLabel: "Headline",
    subtextLabel: "Subtext",
    ctaLabelLabel: "CTA label",
    ctaHrefLabel: "CTA link",
    categoryLabel: "Category",
    titleOverrideLabel: "Title override",
    descriptionOverrideLabel: "Description override",
    enabledLabel: "Enabled",
    addSlideTitle: "Add slide",
    editSlideTitle: "Edit slide",
    addCategoryTitle: "Add category",
    editCategoryTitle: "Edit category",
    image: "Image",
    headline: "Headline",
    order: "Order",
    actions: "Actions",
    edit: "Edit",
    remove: "Remove",
    savedToast: "Saved.",
    removedToast: "Removed.",
  },
};

export function homeLabels(locale: HomeLocale) {
  return locale === "en" ? en : tr;
}
