/**
 * TODO-158A (ADR-086) — Home Experience admin ekranları için yerel etiketler (tr/en).
 * Paylaşılan i18n paketine yalnız nav anahtarı eklendi; ekran metinleri parity riskini
 * azaltmak için burada tutulur (store-admin yerel deseni).
 */
export type HomeLocale = "tr" | "en";

const tr = {
  eyebrow: "Ana Sayfa Deneyimi",
  title: "Ana Sayfa Bölümleri",
  description:
    "Vitrin ana sayfasını yönet: hero slider, öne çıkan kategoriler ve ürün showcase'leri. Sıra vitrinde bu sırayla görünür.",
  newSection: "Yeni bölüm",
  cardTitle: "Bölümler",
  countLabel: "{count} bölüm",
  types: {
    HERO_SLIDER: "Hero Slider",
    FEATURED_CATEGORIES: "Öne Çıkan Kategoriler",
    PRODUCT_SHOWCASE: "Ürün Showcase",
  } as Record<string, string>,
  table: { type: "Tip", title: "Başlık", visibility: "Görünürlük", status: "Durum", order: "Sıra", actions: "İşlemler" },
  enabled: "Aktif",
  disabled: "Pasif",
  visibilityBoth: "Masaüstü + Mobil",
  visibilityDesktop: "Yalnız masaüstü",
  visibilityMobile: "Yalnız mobil",
  visibilityNone: "Gizli",
  manage: "Yönet",
  editSettings: "Ayarlar",
  toggleEnable: "Aktifleştir",
  toggleDisable: "Pasifleştir",
  delete: "Sil",
  moveUp: "Yukarı taşı",
  moveDown: "Aşağı taşı",
  untitled: "(başlıksız)",
  deleteConfirm: "Bu bölümü ve içeriğini silmek istediğinize emin misiniz?",
  createdToast: "Bölüm oluşturuldu.",
  updatedToast: "Bölüm güncellendi.",
  deletedToast: "Bölüm silindi.",
  emptyTitle: "Henüz bölüm yok",
  emptyDescription: "Ana sayfayı oluşturmak için bir hero, öne çıkan kategori veya ürün showcase bölümü ekleyin.",
  emptyAction: "İlk bölümü ekle",
  loadError: "Bölümler yüklenemedi.",
  retry: "Tekrar dene",
  dismiss: "Kapat",
  cancel: "İptal",
  save: "Kaydet",
  saving: "Kaydediliyor…",
  create: "Oluştur",
  form: {
    createTitle: "Yeni bölüm",
    editTitle: "Bölüm ayarları",
    typeLabel: "Bölüm tipi",
    titleLabel: "Başlık",
    subtitleLabel: "Alt başlık (eyebrow)",
    enabledLabel: "Aktif (vitrinde göster)",
    desktopVisibleLabel: "Masaüstünde görünür",
    mobileVisibleLabel: "Mobilde görünür",
    publishStartLabel: "Yayın başlangıcı (opsiyonel)",
    publishEndLabel: "Yayın bitişi (opsiyonel)",
    autoplayLabel: "Otomatik geçiş (ms, 0 = kapalı)",
    layoutLabel: "Düzen",
    layoutCarousel: "Carousel",
    layoutGrid: "Grid",
    maxItemsLabel: "Maksimum ürün",
    sourceLabel: "Kaynak",
    sourceManual: "Manuel (ürün seç)",
    sourceDynamic: "Dinamik (kural)",
    ruleLabel: "Kural",
    rules: {
      NEW_PRODUCTS: "Yeni Ürünler",
      CAMPAIGN: "Kampanyalı Ürünler",
      CATEGORY: "Kategori",
      BRAND: "Marka",
      ATTRIBUTE: "Özellik",
      IN_STOCK: "Stokta",
    } as Record<string, string>,
    categorySlugLabel: "Kategori slug",
    brandLabel: "Marka",
    attributeCodeLabel: "Özellik kodu",
    attributeValueLabel: "Özellik değeri",
  },
  detail: {
    back: "← Bölümlere dön",
    heroTitle: "Hero Slide'ları",
    heroAdd: "Slide ekle",
    heroEmpty: "Henüz slide yok. Tam genişlik hero için bir görsel ekleyin.",
    featuredTitle: "Öne Çıkan Kategoriler",
    featuredAdd: "Kategori ekle",
    featuredEmpty: "Henüz kategori seçilmedi.",
    showcaseTitle: "Showcase Ürünleri",
    showcaseDynamicInfo:
      "Bu showcase DİNAMİK kaynaklıdır; ürünler kurala göre otomatik seçilir. Manuel ürün eklemek için bölüm ayarlarından kaynağı Manuel yapın.",
    showcaseSave: "Ürünleri kaydet",
    productPickerLabel: "Ürünler (seçili sırayla gösterilir)",
    selected: "seçili",
    imageLabel: "Görsel",
    mobileImageLabel: "Mobil görsel (opsiyonel)",
    imageRequired: "Hero görseli zorunludur.",
    headlineLabel: "Başlık",
    subtextLabel: "Alt metin",
    ctaLabelLabel: "CTA metni",
    ctaHrefLabel: "CTA bağlantısı",
    categoryLabel: "Kategori",
    titleOverrideLabel: "Başlık override",
    descriptionOverrideLabel: "Açıklama override",
    enabledLabel: "Aktif",
    addSlideTitle: "Slide ekle",
    editSlideTitle: "Slide düzenle",
    addCategoryTitle: "Kategori ekle",
    editCategoryTitle: "Kategori düzenle",
    image: "Görsel",
    headline: "Başlık",
    order: "Sıra",
    actions: "İşlemler",
    edit: "Düzenle",
    remove: "Kaldır",
    savedToast: "Kaydedildi.",
    removedToast: "Kaldırıldı.",
  },
};

const en: typeof tr = {
  eyebrow: "Home Experience",
  title: "Home Sections",
  description:
    "Manage the storefront home: hero slider, featured categories and product showcases. Order here is the render order on the storefront.",
  newSection: "New section",
  cardTitle: "Sections",
  countLabel: "{count} sections",
  types: {
    HERO_SLIDER: "Hero Slider",
    FEATURED_CATEGORIES: "Featured Categories",
    PRODUCT_SHOWCASE: "Product Showcase",
  },
  table: { type: "Type", title: "Title", visibility: "Visibility", status: "Status", order: "Order", actions: "Actions" },
  enabled: "Enabled",
  disabled: "Disabled",
  visibilityBoth: "Desktop + Mobile",
  visibilityDesktop: "Desktop only",
  visibilityMobile: "Mobile only",
  visibilityNone: "Hidden",
  manage: "Manage",
  editSettings: "Settings",
  toggleEnable: "Enable",
  toggleDisable: "Disable",
  delete: "Delete",
  moveUp: "Move up",
  moveDown: "Move down",
  untitled: "(untitled)",
  deleteConfirm: "Delete this section and its content?",
  createdToast: "Section created.",
  updatedToast: "Section updated.",
  deletedToast: "Section deleted.",
  emptyTitle: "No sections yet",
  emptyDescription: "Add a hero, featured categories or product showcase section to build the home page.",
  emptyAction: "Add first section",
  loadError: "Could not load sections.",
  retry: "Retry",
  dismiss: "Dismiss",
  cancel: "Cancel",
  save: "Save",
  saving: "Saving…",
  create: "Create",
  form: {
    createTitle: "New section",
    editTitle: "Section settings",
    typeLabel: "Section type",
    titleLabel: "Title",
    subtitleLabel: "Subtitle (eyebrow)",
    enabledLabel: "Enabled (show on storefront)",
    desktopVisibleLabel: "Visible on desktop",
    mobileVisibleLabel: "Visible on mobile",
    publishStartLabel: "Publish start (optional)",
    publishEndLabel: "Publish end (optional)",
    autoplayLabel: "Autoplay (ms, 0 = off)",
    layoutLabel: "Layout",
    layoutCarousel: "Carousel",
    layoutGrid: "Grid",
    maxItemsLabel: "Max products",
    sourceLabel: "Source",
    sourceManual: "Manual (pick products)",
    sourceDynamic: "Dynamic (rule)",
    ruleLabel: "Rule",
    rules: {
      NEW_PRODUCTS: "New Products",
      CAMPAIGN: "Campaign Products",
      CATEGORY: "Category",
      BRAND: "Brand",
      ATTRIBUTE: "Attribute",
      IN_STOCK: "In Stock",
    },
    categorySlugLabel: "Category slug",
    brandLabel: "Brand",
    attributeCodeLabel: "Attribute code",
    attributeValueLabel: "Attribute value",
  },
  detail: {
    back: "← Back to sections",
    heroTitle: "Hero Slides",
    heroAdd: "Add slide",
    heroEmpty: "No slides yet. Add an image for the full-width hero.",
    featuredTitle: "Featured Categories",
    featuredAdd: "Add category",
    featuredEmpty: "No categories selected yet.",
    showcaseTitle: "Showcase Products",
    showcaseDynamicInfo:
      "This showcase is DYNAMIC; products are auto-selected by rule. To add manual products, switch the source to Manual in section settings.",
    showcaseSave: "Save products",
    productPickerLabel: "Products (shown in selected order)",
    selected: "selected",
    imageLabel: "Image",
    mobileImageLabel: "Mobile image (optional)",
    imageRequired: "Hero image is required.",
    headlineLabel: "Headline",
    subtextLabel: "Subtext",
    ctaLabelLabel: "CTA label",
    ctaHrefLabel: "CTA link",
    categoryLabel: "Category",
    titleOverrideLabel: "Title override",
    descriptionOverrideLabel: "Description override",
    enabledLabel: "Enabled",
    addSlideTitle: "Add slide",
    editSlideTitle: "Edit slide",
    addCategoryTitle: "Add category",
    editCategoryTitle: "Edit category",
    image: "Image",
    headline: "Headline",
    order: "Order",
    actions: "Actions",
    edit: "Edit",
    remove: "Remove",
    savedToast: "Saved.",
    removedToast: "Removed.",
  },
};

export function homeLabels(locale: HomeLocale) {
  return locale === "en" ? en : tr;
}
